### ISSUE TITLE
Dragonfly Schema Viewer

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/dragonfly-schema#11]
I have a Dragonfly Schema Viewer as a work in progress

![image](https://user-images.githubusercontent.com/547626/74079012-46f52c80-49e6-11ea-8c58-27021a959be7.png)

I am unclear if there is a one-to-one relationship between the Honeybee items and Dragonfly items.

I note things - stories for example - in Dragonfly that I have not yet seen in Honeybee.

I see many "types" in Dragonfly where I am not sure if they are important to parse as 3D models.

Anyway, let it be known that the Dragonfly Schema sample files may be displayed in 3D in your browser reading files directly from the GitHub samples folder. I await further direction as and when more movement is desired.

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour, @chriswmackey can provide more insight but to quickly answer your question the relationship is not one to one. However you can create a honeybee-schema from a dragonfly-schema. I leave the hard question to @chriswmackey.

**Comment by chriswmackey** [comment]
Thanks for getting this together, @theo-armour . There's a one-to-one relationship between Honeybee Room and Dragonfly Room2D. This diagram shows the relationship a little more clearly:
https://docs.google.com/presentation/d/1K1n4GXOGAXNUcf7N_xh4K2VRmZg8TmhJcsqLKdCIrqc/edit?usp=sharing#slide=id.g5dc25bd54e_0_0

Does the viewer display both the Room2D geometry and the ContextShade geometry, @theo-armour ?  Also, I think it would make more sense to display the Room2D geometry as an extruded solids rather than flat, 2D objects.  Coloring the Room2Ds with ProgramType, ConstructionSet, and HVAC would also be helpful.

I'm also thinking it would be nice to have the ability to toggle on/off the display of certain stories so that you won't always have everything previewing on top of other things. At some point, I'll try to get more detailed samples that help illustrate why this is useful (I know the ones in the folder are pretty simple). It's just that the schema has still been undergoing many refactors that I'm not ready to add samples that aren't generated from scripts yet (they will just get outdated within a week and then I have to delete them or else risk having people design for the wrong schema). Hopefully, things settle down soon and I can make some better samples.

**Comment by mostaphaRoudsari** [comment]
I'm going to close this for now as we are already discussing this issue in a different repository. Feel free to reopen the issue if you think otherwise. :)
